apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: artistic-felidae-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: artistic-felidae-python 
  name: artistic-felidae-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: artistic-felidae-python 
