apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: artistic-felidae-python
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:d9485efc91a0c6a781c954ba008030d058b6f5dd@sha256:9612e9d08f15bb4e95a7d334e8115c6267243a4509f1aee5af0d6b5fa68d852e
        name: container-image  
